class CommonWidget {
  static const List<String> contactDetails = [
    "Aaron Hank",
    "Abbey Edward",
    "Abel Reuben",
    "Abelson Hal",
    "Ace Jane",
    "Baba Tupeni",
    "Babbage Charles",
    "Babbitt Milton",
    "Bailey Philip James",
    "Baker Jack",
    "Baker Russell",
    "Ball Hugo",
    "Calvin John",
    "Cameron Kirk",
    "Carey Sandra",
    "Carlin George",
    "Carlson Tucker",
    "Carlyle Thomas",
    "Damon Johnny",
    "Dean Howard",
    "Degas Edgar",
    "Delay Tom",
    "Depew Chauncey",
    "Ecclestone Bernie",
    "Echols Damien",
    "Eckhart Meister",
    "Eddington Arthur Stanley",
    "Edison Thomas Alva",
    "Farmer Frances",
    "Fatiaki Daniel",
    "Faulkner William",
    "Favre Brett",
    "Fawkes Guy",
    "Giacometti, Alberto",
    "Gibbon Edward",
    "Gibran Khalil",
    "Hart Lorenz",
    "Hašek Jaroslav",
    "Hathaway Sybil",
    "Havel Václav",
    "Hazlitt William",
    "Icke David",
    "Idle Eric",
    "Ionesco Eugene",
    "Ishihara Shintaro",
    "James Kevin",
    "James Henry",
    "Jennings Peter",
    "Joan Arc",
    "Johnson Boris",
    "Jordan Sandra",
    "Kalidas",
    "Kapell William",
    "Kasparov Garry",
    "Kelvin Lord",
    "Khan Shahrukh",
    "Kissinger Henry",
    "Lao Tzu",
    "Lawler Jerry",
    "Liddy Gordon",
    "Lyons Steve",
    "Manson Charles",
    "Marquis Don",
    "Newhart Bob",
    "Newton Isaac",
    "Zola Emile"
  ];
}
